- name: Set up Daatabse for Expensive
  hosts: database
  become: yes
  tasks:
  - name: Installing mysql server
    ansible.builtin.package:
      name: mysql-server
      state: present

  - name: System Service file Started
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: Set up Root Password
    ansible.builtin.command: mysql_secure_installation --set-root-pass ExpenseApp@1


